<img src="../images/performances.png" width="100%">

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

### Importing Dataset

In [2]:
df = pd.read_csv('../data/diabetes.csv')

In [3]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

### Checking Null Value

In [4]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
x = df.drop(['Outcome'],axis = 1)

y = df['Outcome']

In [6]:
# !pip install scikit-learn

In [7]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size = 0.20)

### Decision Tree

In [10]:
from sklearn.tree import DecisionTreeClassifier  # load Decision libraries
 
dtc = DecisionTreeClassifier()   # create a decision tree class

dtc.fit(xtrain,ytrain)

dtc.score(xtest,ytest)

0.6883116883116883

### Scope hyper parameter tuing for DT

In [8]:
pred_dtc = dtc.predict(xtest)

from sklearn.metrics import confusion_matrix

cm1 = confusion_matrix(ytest,pred_dtc)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))

accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

specificity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('specificity1 : ', specificity1)

sensitivity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Sensitivity : ', sensitivity1)

from sklearn.metrics import matthews_corrcoef

print("MCC : ",matthews_corrcoef(ytest,pred_dtc))

from sklearn.metrics import roc_auc_score

print("AUC : ",roc_auc_score(ytest,pred_dtc))

from sklearn.metrics import classification_report

print(classification_report(ytest, pred_dtc))

Confusion Matrix : 
 [[87 30]
 [13 24]]
Accuracy :  0.7207792207792207
specificity1 :  0.7435897435897436
Sensitivity :  0.6486486486486487
MCC :  0.351193939778555
AUC :  0.6961191961191961
              precision    recall  f1-score   support

           0       0.87      0.74      0.80       117
           1       0.44      0.65      0.53        37

    accuracy                           0.72       154
   macro avg       0.66      0.70      0.66       154
weighted avg       0.77      0.72      0.74       154



### K-Nearest Neighbors

In [9]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 9)

knn.fit(xtrain,ytrain)

knn.score(xtest,ytest)

0.7792207792207793

In [ ]:
# Scopre of hyper parameter tuning

In [10]:
pred_knn = knn.predict(xtest)

from sklearn.metrics import confusion_matrix

cm1 = confusion_matrix(ytest,pred_knn)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))

accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

specificity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('specificity1 : ', specificity1)

sensitivity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Sensitivity : ', sensitivity1)

from sklearn.metrics import matthews_corrcoef

print("MCC : ",matthews_corrcoef(ytest,pred_knn))

from sklearn.metrics import roc_auc_score

print("AUC : ",roc_auc_score(ytest,pred_knn))

from sklearn.metrics import classification_report

print(classification_report(ytest, pred_knn))

Confusion Matrix : 
 [[94 23]
 [11 26]]
Accuracy :  0.7792207792207793
specificity1 :  0.8034188034188035
Sensitivity :  0.7027027027027027
MCC :  0.46425425741937526
AUC :  0.753060753060753
              precision    recall  f1-score   support

           0       0.90      0.80      0.85       117
           1       0.53      0.70      0.60        37

    accuracy                           0.78       154
   macro avg       0.71      0.75      0.73       154
weighted avg       0.81      0.78      0.79       154



### Random Forest

In [11]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()

rfc.fit(xtrain,ytrain)

rfc.score(xtest,ytest)

0.7857142857142857

#### Scope of hyper parameter tuning  and corss validations

In [12]:
pred_rfc = rfc.predict(xtest)

from sklearn.metrics import confusion_matrix

cm1 = confusion_matrix(ytest,pred_rfc)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))

accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

specificity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('specificity1 : ', specificity1)

sensitivity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Sensitivity : ', sensitivity1)

from sklearn.metrics import matthews_corrcoef

print("MCC : ",matthews_corrcoef(ytest,pred_rfc))

from sklearn.metrics import roc_auc_score

print("AUC : ",roc_auc_score(ytest,pred_rfc))

from sklearn.metrics import classification_report

print(classification_report(ytest, pred_rfc))

Confusion Matrix : 
 [[95 22]
 [11 26]]
Accuracy :  0.7857142857142857
specificity1 :  0.811965811965812
Sensitivity :  0.7027027027027027
MCC :  0.47473127343114396
AUC :  0.7573342573342574
              precision    recall  f1-score   support

           0       0.90      0.81      0.85       117
           1       0.54      0.70      0.61        37

    accuracy                           0.79       154
   macro avg       0.72      0.76      0.73       154
weighted avg       0.81      0.79      0.79       154



### Logistic Regression

In [11]:
from sklearn.linear_model import LogisticRegression

logReg = LogisticRegression()

logReg.fit(xtrain,ytrain)

logReg.score(xtest,ytest)

C:\Users\panka\anaconda33\envs\cv\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.7272727272727273

#### scope of  hyper parameter tuning and cross validations

In [14]:
pred_logReg = logReg.predict(xtest)

from sklearn.metrics import confusion_matrix

cm1 = confusion_matrix(ytest,pred_logReg)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))

accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

specificity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('specificity1 : ', specificity1)

sensitivity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Sensitivity : ', sensitivity1)

from sklearn.metrics import matthews_corrcoef

print("MCC : ",matthews_corrcoef(ytest,pred_logReg))

from sklearn.metrics import roc_auc_score

print("AUC : ",roc_auc_score(ytest,pred_logReg))

from sklearn.metrics import classification_report

print(classification_report(ytest, pred_logReg))

Confusion Matrix : 
 [[96 21]
 [13 24]]
Accuracy :  0.7792207792207793
specificity1 :  0.8205128205128205
Sensitivity :  0.6486486486486487
MCC :  0.4407543676618945
AUC :  0.7345807345807346
              precision    recall  f1-score   support

           0       0.88      0.82      0.85       117
           1       0.53      0.65      0.59        37

    accuracy                           0.78       154
   macro avg       0.71      0.73      0.72       154
weighted avg       0.80      0.78      0.79       154



### Support Vector Machine (Linear)

In [15]:
from sklearn.svm import SVC

svml = SVC(kernel = 'linear')

svml.fit(xtrain,ytrain)

svml.score(xtest,ytest)

0.7987012987012987

#### scope of  hyper parameter tuning and cross validations

In [16]:
pred_svml = svml.predict(xtest)

from sklearn.metrics import confusion_matrix

cm1 = confusion_matrix(ytest,pred_svml)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))

accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

specificity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('specificity1 : ', specificity1)

sensitivity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Sensitivity : ', sensitivity1)

from sklearn.metrics import matthews_corrcoef

print("MCC : ",matthews_corrcoef(ytest,pred_svml))

from sklearn.metrics import roc_auc_score

print("AUC : ",roc_auc_score(ytest,pred_svml))

from sklearn.metrics import classification_report

print(classification_report(ytest, pred_svml))

Confusion Matrix : 
 [[97 20]
 [11 26]]
Accuracy :  0.7987012987012987
specificity1 :  0.8290598290598291
Sensitivity :  0.7027027027027027
MCC :  0.4963873813774586
AUC :  0.7658812658812658
              precision    recall  f1-score   support

           0       0.90      0.83      0.86       117
           1       0.57      0.70      0.63        37

    accuracy                           0.80       154
   macro avg       0.73      0.77      0.74       154
weighted avg       0.82      0.80      0.81       154



### Support Vector Machine (RBF)

In [17]:
from sklearn.svm import SVC

svmr = SVC(kernel = 'rbf')

svmr.fit(xtrain,ytrain)

svmr.score(xtest,ytest)

0.8311688311688312

### scope of  hyper parameter tuning and cross validations

In [18]:
pred_svmr = svmr.predict(xtest)

from sklearn.metrics import confusion_matrix

cm1 = confusion_matrix(ytest,pred_svmr)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))

accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

specificity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('specificity1 : ', specificity1)

sensitivity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Sensitivity : ', sensitivity1)

from sklearn.metrics import matthews_corrcoef

print("MCC : ",matthews_corrcoef(ytest,pred_svmr))

from sklearn.metrics import roc_auc_score

print("AUC : ",roc_auc_score(ytest,pred_svmr))

from sklearn.metrics import classification_report

print(classification_report(ytest, pred_svmr))

Confusion Matrix : 
 [[106  11]
 [ 15  22]]
Accuracy :  0.8311688311688312
specificity1 :  0.905982905982906
Sensitivity :  0.5945945945945946
MCC :  0.5212132688864239
AUC :  0.7502887502887504
              precision    recall  f1-score   support

           0       0.88      0.91      0.89       117
           1       0.67      0.59      0.63        37

    accuracy                           0.83       154
   macro avg       0.77      0.75      0.76       154
weighted avg       0.83      0.83      0.83       154



# Hyper Parameter tuning 

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from scipy import stats
#from sklearn.cross_validation import KFold, cross_val_score, train_test_split

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize 
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import mean_squared_error as mse
from sklearn.feature_selection import RFECV
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.preprocessing import Normalizer
from sklearn.pipeline import Pipeline
from sklearn.pipeline import FeatureUnion
from sklearn.feature_selection import SelectKBest
from sklearn import datasets
from sklearn.model_selection import cross_validate
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings("ignore")

In [49]:
# Define parameters for optimization using dictionaries {parameter name: parameter list}

# SVM_params = {'C':[0.001, 0.1, 10, 100], 'kernel':['rbf' ,'linear', 'poly', 'sigmoid']}
LR_params = {'C':[0.001, 0.1, 1, 10, 100]}
LDA_params = {'n_components':[None, 1,2,3], 'solver':['svd'], 'shrinkage':[None]}
KNN_params = {'n_neighbors':[1,5,10,9,20, 50], 'p':[2], 'metric':['minkowski']}
RF_params = {'n_estimators':[10,50,100]}
DTC_params = {'criterion':['entropy', 'gini'], 'max_depth':[10, 50, 100]}

In [50]:
# Append list of models with parameter dictionaries

models_opt = []

models_opt.append(('LR', LogisticRegression(), LR_params))
models_opt.append(('LDA', LinearDiscriminantAnalysis(), LDA_params))
models_opt.append(('KNN', KNeighborsClassifier(),KNN_params))
models_opt.append(('DTC', DecisionTreeClassifier(), DTC_params))
models_opt.append(('RFC', RandomForestClassifier(), RF_params))
# models_opt.append(('SVM', SVC(), SVM_params))

In [51]:
models_opt

[('LR', LogisticRegression(), {'C': [0.001, 0.1, 1, 10, 100]}),
 ('LDA',
  LinearDiscriminantAnalysis(),
  {'n_components': [None, 1, 2, 3], 'solver': ['svd'], 'shrinkage': [None]}),
 ('KNN',
  KNeighborsClassifier(),
  {'n_neighbors': [1, 5, 10, 9, 20, 50], 'p': [2], 'metric': ['minkowski']}),
 ('DTC',
  DecisionTreeClassifier(),
  {'criterion': ['entropy', 'gini'], 'max_depth': [10, 50, 100]}),
 ('RFC', RandomForestClassifier(), {'n_estimators': [10, 50, 100]})]

In [63]:
from sklearn.model_selection import LeaveOneOut
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
#from sklearn.cross_validation.KFold(n=4, n_folds=2, shuffle=False,random_state=None)
from sklearn.model_selection import StratifiedKFold
skfold=StratifiedKFold(n_splits=5)

In [64]:
import time
start = time.time()
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.25 , random_state = 0)
end = time.time()
print("Time consumed in working: ",end - start)

Time consumed in working:  0.0019998550415039062


In [67]:
results = []
names = []


def estimator_function(parameter_dictionary, scoring = 'accuracy'):
    
    
    for name, model, params in models_opt:
    
        #kfold = KFold(len(X_train), n_folds=5, random_state=2, shuffle=True)
        skfold=StratifiedKFold(n_splits=5)
        leave_validation=LeaveOneOut()

        model_grid = GridSearchCV(model, params)

        cv_results = cross_val_score(model_grid, X_train, Y_train, cv =leave_validation, scoring=scoring)

        results.append(cv_results)

        names.append(name)

        msg = "Cross Validation Accuracy %s: Accarcy: %f SD: %f" % (name, cv_results.mean(), cv_results.std())

        print(msg)

In [ ]:
estimator_function(models_opt, scoring = 'accuracy')

Cross Validation Accuracy LR: Accarcy: 0.751736 SD: 0.432006
Cross Validation Accuracy LDA: Accarcy: 0.750000 SD: 0.433013
Cross Validation Accuracy KNN: Accarcy: 0.701389 SD: 0.457649
Cross Validation Accuracy DTC: Accarcy: 0.647569 SD: 0.477727


In [ ]:
# leave_validation=LeaveOneOut()  
Cross Validation Accuracy LR: Accarcy: 0.751736 SD: 0.432006
Cross Validation Accuracy LDA: Accarcy: 0.750000 SD: 0.433013
Cross Validation Accuracy KNN: Accarcy: 0.701389 SD: 0.457649
Cross Validation Accuracy DTC: Accarcy: 0.637153 SD: 0.480821
Cross Validation Accuracy RFC: Accarcy: 0.736111 SD: 0.440740

## Random Forest

In [25]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt','log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 1000,10)]
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10,14]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4,6,8]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
              'criterion':['entropy','gini']}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 120, 230, 340, 450, 560, 670, 780, 890, 1000], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [26]:
rf=RandomForestClassifier()
rf_randomcv=RandomizedSearchCV(estimator=rf,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,
                               random_state=100,n_jobs=-1)
### fit the randomized model
rf_randomcv.fit(X_train,Y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 120, 230, 340, 450,
                                                      560, 670, 780, 890,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [27]:
rf_randomcv.best_params_

{'n_estimators': 2000,
 'min_samples_split': 14,
 'min_samples_leaf': 2,
 'max_features': 'auto',
 'max_depth': 10,
 'criterion': 'entropy'}

In [28]:
best_random_grid=rf_randomcv.best_estimator_

In [29]:
from sklearn.metrics import accuracy_score
y_pred=best_random_grid.predict(X_test)
print(confusion_matrix(Y_test,y_pred))
print("Training Accuracy Score {}".format(best_random_grid.score(X_train,Y_train)))
print("Testing Accuracy Score {}".format(accuracy_score(Y_test,y_pred)))
print("Classification report: {}".format(classification_report(Y_test,y_pred)))

[[117  13]
 [ 30  32]]
Training Accuracy Score 0.9114583333333334
Testing Accuracy Score 0.7760416666666666
Classification report:               precision    recall  f1-score   support

           0       0.80      0.90      0.84       130
           1       0.71      0.52      0.60        62

    accuracy                           0.78       192
   macro avg       0.75      0.71      0.72       192
weighted avg       0.77      0.78      0.77       192



In [ ]:
cm1 = confusion_matrix(Y_test,y_pred)
print('Confusion Matrix : \n', cm1)

total1=sum(sum(cm1))

accuracy1=(cm1[0,0]+cm1[1,1])/total1
print ('Accuracy : ', accuracy1)

specificity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
print('specificity1 : ', specificity1)

sensitivity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
print('Sensitivity : ', sensitivity1)

from sklearn.metrics import matthews_corrcoef

print("MCC : ",matthews_corrcoef(ytest,pred_svmr))

from sklearn.metrics import roc_auc_score

print("AUC : ",roc_auc_score(ytest,pred_svmr))

from sklearn.metrics import classification_report

print(classification_report(ytest, pred_svmr))

In [ ]:
Training Accuracy Score 0.9114583333333334
Testing Accuracy Score 0.7760416666666666
precision    
recall  
f1-score

In [30]:
(80+71)/2

75.5

<img src="../images/confusion_Matrix.jpeg" width="70%">

In [33]:
TP = 117
FN = 30
FP = 13
TN = 32

In [34]:
# Random forest
def fun(TP,FN,FP,TN):
    print("Random Forest on BCWD")
    print("TP",TP)
    print("FN",FN)
    print("FP",FP)
    print("TN", TN)
    Accuracy = (TP + TN)/(TP + TN + FP + FN)
    print("Accuracy : {}".format(Accuracy))
    Precision = TP / (TP + FP)
    print("Precision : {}".format(Precision))
    Recall = TP / (TP + FN)
    print("Recall : {} ".format(Recall))
    F1_score = 2*(Precision*Recall)/(Precision + Recall)
    print("F1_score : {}".format(F1_score))
    TPR = TP / (TP + FP)
    print("TPR : {}".format(TPR))
    FPR = FP / (FP + TN)
    print("FPR : {}".format(FPR))

In [35]:
fun(TP,FN,FP,TN)

Random Forest on BCWD
TP 117
FN 30
FP 13
TN 32
Accuracy : 0.7760416666666666
Precision : 0.9
Recall : 0.7959183673469388 
F1_score : 0.8447653429602888
TPR : 0.9
FPR : 0.28888888888888886


<img src="../images/performances.png" width="100%">

# SVM

In [38]:
from contextlib import contextmanager
@contextmanager
def timer():
    """Helper for measuring runtime"""

    time0 =  time.perf_counter()
    
    yield
    print('[elapsed time: %.18f s]' % (time.perf_counter() - time0))

In [39]:
from sklearn.metrics import classification_report # make predictions on validation datasets
import time
with timer() as t:
    SVM = SVC(C=1.0,
    kernel='rbf',
    degree=6,
    gamma='scale',
    coef0=0.0,
    shrinking=True,
    probability=False,
    tol=0.001,
    cache_size=300,
    class_weight=None,
    verbose=False,
    max_iter=-1,
    decision_function_shape='ovr',
    break_ties=False,
    random_state=None)
    
    SVM.fit(X_train, Y_train)
    predictions= SVM.predict(X_test)
    print(("training score : {}").format(SVM.score(X_train, Y_train)))
    print(("testing score : {}").format(accuracy_score(Y_test, predictions)))
    print(classification_report(Y_test, predictions))
    print(confusion_matrix(Y_test, predictions))

training score : 0.7586805555555556
testing score : 0.7708333333333334
              precision    recall  f1-score   support

           0       0.78      0.92      0.84       130
           1       0.72      0.47      0.57        62

    accuracy                           0.77       192
   macro avg       0.75      0.69      0.71       192
weighted avg       0.76      0.77      0.76       192

[[119  11]
 [ 33  29]]
[elapsed time: 0.115074800000002142 s]


In [41]:
#
TP1 = 119
FP1 = 11
FN1 = 33
TN1 = 29


def fun1(TP,FN,FP,TN):
    
    print("SVM on BCWD ---------------------->")
    print("TP",TP)
    print("FN",FN)
    print("FP",FP)
    print("TN", TN)
    Accuracy = (TP + TN)/(TP + TN + FP + FN)
    print("Accuracy : {}".format(Accuracy))
    Precision = TP / (TP + FP)
    print("Precision : {}".format(Precision))
    Recall = TP / (TP + FN)
    print("Recall : {} ".format(Recall))
    F1_score = 2*(Precision*Recall)/(Precision + Recall)
    print("F1_score : {}".format(F1_score))
    TPR = TP / (TP + FP)
    print("TPR : {}".format(TPR))
    FPR = FP / (FP + TN)
    print("FPR : {}".format(FPR))

In [42]:
fun1(TP1,FN1,FP1,TN1)

SVM on BCWD ---------------------->
TP 119
FN 33
FP 11
TN 29
Accuracy : 0.7708333333333334
Precision : 0.9153846153846154
Recall : 0.7828947368421053 
F1_score : 0.8439716312056739
TPR : 0.9153846153846154
FPR : 0.275


<img src="../images/performances.png" width="100%">

In [ ]:
Observations : 

# KNN

In [43]:
KNN_params = {'n_neighbors':[1,5,10,9,20, 50], 'p':[2], 'metric':['minkowski']}

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 9)

knn.fit(xtrain,ytrain)

knn.score(xtest,ytest)